### ISSUE TITLE
Parsing error for comment before protocol

### ISSUE THREAD

**Issue by caspermeijn** [opwvhk/avro-schema-support#12]
Today I received an AVDL for the first time from a supplier. With this great plugin I was able to comprehend the contents quickly. Thanks for that!

I found a problem with parsing of this received file. I was able to pin-point it to the comment between the version and the protocol. After removing the comment the file was parsed correctly.

Below is a simplified code example:
```
@version("1.0.0")

/**
 Multi line Comment about the message
 Multi line Comment about the message
 */
protocol MyProtocol {
}

```

**Comment by opwvhk** [comment]
Thank you for the example; this is really helpful.

The tricky bit with comments in `.avdl` files is that Avro accepts them almost everywhere.

For example, the following example shows errors in the plugin but Avro happily allows it (and attributes the comment inside `Plain` to the next record `Commented`):
```
protocol MyProtocol {
    record Plain {
        int number; /** record comment */
    }
    record Commented {
        string text;
    }
}
```

It was a conscious decision not to support every case.

Having said that, switching annotations and comments is not as weird as the example above, so the upcoming will no longer choke on it.

**Comment by caspermeijn** [comment]
Thank you for your reaction. I tested version 203.0.2 and it works with the given example. However I found that my simplified example was too simple. The received file can still not be parsed because of another comment before the version. 

Below is a new simplified example:
```
/**
 * Copyright notice
 */
@version("1.0.0")

/**
 Multi line Comment about the message
 Multi line Comment about the message
 */
protocol MyProtocol {
}
```

I understand the struggles with the comments. In Xtext (a tool to create domain specific languages) you can specify that comments are hidden for the parser, therefore comments can be everywhere in the code. Maybe such a thing also exists for IntelliJ.

**Comment by opwvhk** [comment]
I can do that, but this would also remove the documentation comments from the elements. This in turn affects error handling by the parser, formatting, etc. Besides, it is actually a semantic error to specify two documentation comments for an element &mdash; the IDL parser will only use the last one.

I'll see if I can rework it as a warning (dangling doc comment).

**Comment by opwvhk** [comment]
The adjustments look good at first glance. Uploaded version 203.1.0.

**Comment by caspermeijn** [comment]
This fixes parsing the files. I have some ` Dangling documentation warning`s in the files, but navigating the files works fine. I will report the warnings to the supplier.

Thanks for solving this issue!

**Comment by opwvhk** [comment]
Correct: I've added these warnings, as the Avro IDL parser will ignore them.
