### ISSUE TITLE
Fails to convert .avdl file to either .avsc or .avpr file

### ISSUE THREAD

**Issue by q3769-patientpoint** [opwvhk/avro-schema-support#166]
**Description**

Simple won't convert from .avdl to anything

**To Reproduce**

Steps to reproduce the behaviour:
1. Start with a valid .avdl file (e.g. one generated from an existing/valid .avsc file)
2. Try 
2.1. either: Refactor -> Convert Avro IDL to Avro Protocol
2.2. or: Refactor -> Convert Avro IDL to Avro Schmema
4. Click "Save" when asked.

**Expected behaviour**

Result in newly generated .avpr or .avsc file.

**Screenshots**

![image](https://github.com/user-attachments/assets/914905d8-75a8-4d58-8af5-7c609d441bd2)

![image](https://github.com/user-attachments/assets/ff22d178-d763-4cfe-9425-b24febb1944a)

**Versions:**
IntelliJ IDEA 2024.2.0.2 (Ultimate Edition)
Build #IU-242.20224.419, built on August 19, 2024
 - Plugin: Version 223.3.1

**Additional context**

This should be some regression bug. It used to work.

**Comment by opwvhk** [comment]
Thank you for this detailed bug report!

For my understanding, it's easier to split this, as this report describes two bugs:

1. the implicit assumption that a `.avdl` file always contains a protocol (this is no longer true)
2. the failure to create a `.avsc` file

I've created issues #168 and #169 to track both of them.

**Comment by opwvhk** [comment]
Closing this issue now, as both bugs are tracked (and will be fixed) separately.
