### ISSUE TITLE
Idea 2024.3 is not supported

### ISSUE THREAD

**Issue by kortov** [opwvhk/avro-schema-support#191]
**Description**
Plugin isn't compatible with the latest Idea's verision, please update the plugin

**Screenshots**

![image](https://github.com/user-attachments/assets/0fc36a3c-7b3c-4dc9-8646-3ffd10eb9b13)

**Versions:**
 - JetBrains Product: [e.g. IntelliJ Ultimate]
 - Version [e.g. 2024.3]
 - Plugin: [e.g. 223.3.1]

**Comment by opwvhk** [comment]
Yes, this is (was?) a known problem. In the next release (2024.3), the JSON plugin will be a separate, bundled plugin. It should work:
* I've tested it locally with both the oldest supported version (2023.2) and the 2024.3 EAP: both work
* The plugin verifier gives an error, but this is documented as a false positive. Both on the development Slack channels and the support page, JetBrains says that this error can be ignored: https://intellij-support.jetbrains.com/hc/en-us/community/posts/21479962703890-JSON-plugin-dependency-cannot-be-resolved
* However, the marketplace team still reduced the until build to 242.* (i.e. 2024.2.x)...

I've manually set it to 243 to support 2024.3RC1. Now hoping it's allowed by JetBrains... 🤞

**Comment by jmntn2000** [comment]
Same issue since 2024.3 update in ultimate.  Wouldn't not have upgraded if I knew this plugin would not work.

**Comment by jmntn2000** [comment]
> Thank you both for reporting this. Unfortunately, this is not my doing: JetBrains forcibly set the until build back to 242.* (2024.2), causing the plugin to stop working. This is odd, because I've tested the plugin to work with 2024.3, and because the error in the plugin verifier is a known false positive (a bug, due to be fixed this week)...

Thank you for the update.  Oh and also thank you for an awesome plugin, that I frequently use:)

**Comment by opwvhk** [comment]
Version 232.0.1 is now available, and supports 2024.3 (so far 🤞).

**Comment by jmntn2000** [comment]
Working great now, thank you!
