### ISSUE TITLE
213.0.0 keeps opening a changelog dialog in every project

### ISSUE THREAD

**Issue by PawelLipski** [opwvhk/avro-schema-support#22]
Thanks for maintaining the plugin, it's pretty useful :)

After the update to 213.0.0, this dialog opens every time any project is opened (also, re-opened) in my IntelliJ Ultimate 2022.1:

![image](https://user-images.githubusercontent.com/3383210/163371020-d1625f48-4d51-45e7-9fc5-e65528651992.png)

TBH that's uncommon for plugin to display such custom dialogs after an update 🤔 also, there's no way to deactivate the dialog

Also, the changelog is empty 😅

**Comment by opwvhk** [comment]
Thank you for reporting this!  Although changelog is not unheard of (I copied the idea from the asciidoc plugin), it most certainly should not popup every time! I'll publish an update to fix this soon.

**Comment by opwvhk** [comment]
I've published a patch release. It was approved by JetBrains in record time 😁.
