### ISSUE TITLE
incompatible with build IC-222.3345.118

### ISSUE THREAD

**Issue by jkt628** [opwvhk/avro-schema-support#26]
**Description**
snap upgraded intellij-idea-community to 2022.2 and now plugin shows incompatible

**To Reproduce**

1. Go to File / Settings
2. Click on Plugins, then Installed
3. Scroll down to Apache Avro IDL Schema Support

**Expected behavior**

support 2022.2

**Screenshots**
![image](https://user-images.githubusercontent.com/4302889/181056456-e05b3822-7d62-4093-b091-9a931139eef8.png)

**Versions:**
 - JetBrains Product: intellij-idea-community (snap)
 - Version 2022.2

**Additional context**

**Comment by opwvhk** [comment]
Thank you for reporting this Jack,

I've had some busy weeks, so I didn't get around to updating yet, including a few changes I've had ready for a few weeks now.

At least the next update is now pending approval from JetBrains, so this should be sorted in a few days.

**Comment by jkt628** [comment]
many thanks, @opwvhk

**Comment by opwvhk** [comment]
The release has been approved. Closing this issue.
