### ISSUE TITLE
Avro Schema language injection

### ISSUE THREAD

**Issue by phemmer** [opwvhk/avro-schema-support#5]
First off thanks for creating this. There's been a major lack of plugins that support Avro schemas for Intellij.

Would it be possible to add the ability to use Avro schema as a [language injection](https://www.jetbrains.com/help/idea/using-language-injections.html)? Currently the only option for injection is AvroIDL

![image](https://user-images.githubusercontent.com/1826947/106405144-30b85b80-6403-11eb-8ce4-5d2d93384f1a.png)

Thanks

**Comment by opwvhk** [comment]
Good idea! Currently, support for `.avcs` & `.avpr` sources is in its infancy. I did not define a language for it, but essentially defined them to be "JSON + a JSON schema".

To support language injection, I'll need to define languages for it. However, I do not know how to define a language that inherits all the stuff Jetbrains already built for JSON. If I define the language "Avro Schema", using JSON as a base language, I get an exception: "Language: JSON5 != Language: AvroSchema".

Any ideas?

**Comment by phemmer** [comment]
Ah, sorry, no idea :-(
I've never written a plugin for IntelliJ, so I have no idea how it all works.

Trying to think of any languages that do something similar (json w/schema) that can be examined to see how they did it, but nothing comes to mind. Though looking through the list, there's certainly tons of SQL languages. Maybe they do something similar?

**Comment by opwvhk** [comment]
Found it: after creating the schema and protocol languages and associating them with the file types, I also need to:
1. Extend `JsonParserDefinition` to create a `JsonFileImpl` for each of the languages
2. Copy `Json5PsiWalkerFactory` to also create a walker for both languages
3. Register the extensions defined in steps 1 & 2

**Comment by opwvhk** [comment]
New version is available in the plugin marketplace.
