### ISSUE TITLE
not supported in 2021.1

### ISSUE THREAD

**Issue by xmlking** [opwvhk/avro-schema-support#6]
![image](https://user-images.githubusercontent.com/627951/106640238-aa069a00-653a-11eb-8243-7fd71213ef22.png)

**Comment by opwvhk** [comment]
Thank you for reporting this. It's a known issue, as I'm currently (also) targetting the 2020.2 version of IntelliJ.

My plan is to upgrade the requirements in the very near future, and then I can also support 2021.1.

**Comment by opwvhk** [comment]
Uploaded snapshot release to support 2021.1 EAP.

**Comment by opwvhk** [comment]
New version is available in the plugin marketplace.
